### ISSUE TITLE
Code compilation on the arm based processors like Raspberry PI

### ISSUE THREAD

**Issue by blacksocket** [danielschramm/qt_inverter_10k#1]
Hello,

Is this possible to compile your code on the arm based processors like Raspberry PI ? I tried to compile it on RPI 2 armv7l and getting an error :

pi@raspberrypi:/opt/ha-inverter-mqtt-agent/sources/qt_inverter_10k $ cmake . && make
CMake Error: The source directory "/opt/ha-inverter-mqtt-agent/sources/qt_inverter_10k" does not appear to contain CMakeLists.txt.

**Comment by danielschramm** [comment]
Please try with qmake instead of cmake - it should be possible if all QT Libs are installed correctly.

**Comment by blacksocket** [comment]
Do I need first I need to setup the whole Cross-compilation environment for Qt 5 ?
https://www.raspberrypi.org/forums/viewtopic.php?t=204529

"Info: creating stash file /opt/ha-inverter-mqtt-agent/sources/qt_inverter_10k/.qmake.stash
Project ERROR: Unknown module(s) in QT: mqtt"

What is the exact procedure for linux ?

qmake -query QT_INSTALL_LIBS
mkdir src
cd src
-> checkout correct version to match qt installation from: git://code.qt.io/qt/qtmqtt.git
cd qtmqtt
qmake
gmake
gmake install (you may need administrator privileges for this)

Thank you!

**Comment by danielschramm** [comment]
First step is to install a QT dev environment.
From deb Packages in Raspbian, Debian, Ubuntu, ... it's a lot of digging around to find all necessary packages, it's easier to do a full install which takes some time and lot of space:
```
sudo apt install `apt-cache search qt | grep 5- | grep -v gles | grep ^qt | awk '{print $1}' | xargs `
sudo apt install `apt-cache search libqt5 | grep -v gles | grep ^libqt | awk '{print $1}' | xargs`
```
 
Next you need to find out which release of QT Libs are installed -> it is important for getting the correct qtmqtt package. for example 5.12 package will not compile against 5.11, ...
Than you can use GIT to fetch the correct branch of qtmqtt or you can go with a webbrowser through the branches list: https://github.com/qt/qtmqtt/branches/all and fetch the sources as a zip file. Then you need to compile qtmqtt (you posted the instruction above).

After that my project should just compile without any issues.

**Comment by blacksocket** [comment]
Ok, thank you!

**Comment by danielschramm** [comment]
Did it compile or do you need some more information?
Can we close this issue?

**Comment by blacksocket** [comment]
You can close the issue. Thank you!
