### ISSUE TITLE
GeneralStatus: wrong Format

### ISSUE THREAD

**Issue by blacksocket** [danielschramm/qt_inverter_10k#2]
Hello,

I just launched the windows binary version with P17 protocol configured and getting the below errors. Do you know what could be wrong ?

qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No TLS backend is available
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No functional TLS backend was found
connecting...
connected...
Connected to mqtt broker
15  bytes written...
"^D01100000000\xDC\xC0\r"
8  bytes written...
"^D10100000,00024"
PowerStatus: wrong Format
8  bytes written...
",,+00022,+00015,+00019,+00056,0000,0000,0001,00001,0114,0139,0160,00413,004,1,0,1,1,1,1\b\xA5\r^D1100000,3390,0"
GeneralStatus: wrong Format
12  bytes written...
"000,0006,0540,099,+00014,2294,2320,2298,5000,0000,0000,0000,2294,2320,2298,4999,,,,029,032,000,0\xFA\x83\r^D0300,00000,000"
EmInfo: wrong Format
8  bytes written...
"00,00000,00000,1\xA7\x1D\r^D011000040026s\r"
TotalEnergy: wrong Format
15  bytes written...
"^D01100000000\xDC\xC0\r"
8  bytes written...
"^D10100000,00024"
PowerStatus: wrong Format
8  bytes written...
",,+00019,+00014,+00018,+00051,0000,0000,0000,00000,0114,0139,0160,00413,004,1,0,1,1,1,1\xA5""8\r^D1100000,3382,0"
GeneralStatus: wrong Format
12  bytes written...
"000,0007,0540,099,+00014,2300,2324,2294,4998,0000,0000,0000,2298,2326,2294,4999,,,,029,032,000,0\x0B""C\r^D0300,00000,000"
EmInfo: wrong Format
8  bytes written...
"00,00000,00000,1\xA7\x1D\r^D011000040026s\r"
TotalEnergy: wrong Format
15  bytes written...
"^D01100000000\xDC\xC0\r"
8  bytes written...
"^D10100000,00023"
PowerStatus: wrong Format
8  bytes written...
",,+00017,+00011,+00016,+00044,0000,0001,0000,00001,0115,0139,0160,00414,004,1,0,1,1,1,1G\xE0\r^D1100000,3360,0"
GeneralStatus: wrong Format
12  bytes written...
"000,0007,0540,099,+00014,2303,2324,2292,4998,0000,0000,0000,2303,2326,2292,4999,,,,029,032,000,0\xFF\x13\r^D0300,00000,000"

**Comment by danielschramm** [comment]
Hello,

The TLS Messages are normal, just ignore them.

For the format this application very much relies on the line detection of the serial to network converter.
If you have the serial port directly connected to the Raspberry or use an usb-serial adapter it will currently not work.

In your logs you can find a "\r" in a receive line. That has to be eliminated by the Serial-Network bidge. "\r" is only alloed as line end.

You need to setup the converter to generate an transmission for every line either by "\r" line identification or by setting a character timeout correctly.
For me it works with 1000ms timeout but you could also set 0x0d ad delimiting character:

![image](https://user-images.githubusercontent.com/7165994/143762826-4ed7d795-d9f4-45ce-ae88-8cc01e9db27e.png)

Hope this helps and you get it running without any more issues.

Daniel

**Comment by blacksocket** [comment]
I am using USR-W610 https://www.pusr.com/download/WIFI/USR-W610-User-Manual-V1.0.1.01.pdf
The current configuration looks like this:

![image](https://user-images.githubusercontent.com/13651344/143764970-3f202f59-e5bc-4d95-8662-e4b03c6676bf.png)

However there is possibility to enable Registered Package Type "Upload Manner: first：Module send registration packet when connection established；every：Send registration packet every time when module send data". Not sure if this is what should be configured:

![image](https://user-images.githubusercontent.com/13651344/143765042-898356c3-4382-4e1a-89dc-385eb47b4402.png)
Upload Manner i can select first or every.

**Comment by danielschramm** [comment]
Hello,

I do not have the same model so my questions are only hints where you could try some changes.

1. 485 mode should be disabled since we are not using RS485 here. Everything in the first Box looks ok to me.
2. Which Options are shown whet you set "Uart AutoFrame" to enabled?
3. Registered Package is new to me. Can it be completely disabled or otherwise set it to first and try to set an empty "Registration package"?

Good Luck.
Daniel

**Comment by blacksocket** [comment]
The "Uart AutoFrame" show this below. I tried "AutoFrame Time(100~10000)(ms)" with 1000 without success:

![image](https://user-images.githubusercontent.com/13651344/143788034-d5b336cd-19a6-4c12-9752-90574c9d06c2.png)

I tried different configurations and one of them was the result below:

qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No TLS backend is available
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No functional TLS backend was found
connecting...
connected...
Connected to mqtt broker
15  bytes written...
""
EnergyYear: wrong Format
8  bytes written...
""
PowerStatus: wrong Format
8  bytes written...
""
GeneralStatus: wrong Format
12  bytes written...

**Comment by danielschramm** [comment]
Auto Frame seems not only to wait for the timeout. Instead it also needs a fixed char count.
Please disable that.

**Comment by danielschramm** [comment]
Can you make a Screenshot of the Mode Selektion?

From the manual: 
"3.1.1.Transparent transmission mode"
With
"3.2.2.Serial Free-Frame mode"
Should work, but is not shown in the shots.

**Comment by blacksocket** [comment]
It has been setup with STA transparent mode:

![image](https://user-images.githubusercontent.com/13651344/143867991-f18e8068-dc76-40aa-a0d7-9f95d615e6a5.png)

Other possibilities below:

![image](https://user-images.githubusercontent.com/13651344/143868665-747cd955-3a48-4025-bcd1-377fdcf8db41.png)

**Comment by danielschramm** [comment]
That setting is ok.
Did you find the settings from ""3.2.2.Serial Free-Frame mode""

**Comment by blacksocket** [comment]
The only other setting i found is the below one:

![image](https://user-images.githubusercontent.com/13651344/143957537-9d695992-f0f1-4d9a-9e3c-3925fe849ea2.png)

I can't see anything like  "3.2.2.Serial Free-Frame mode":

W610 will continually check the interval between two adjacent bytes when W610 receives the data from serial
side. If this interval > serial Free-Frame triggering time (Default is 50ms and user can use AT commend to
configure triggering time), it will be considered as end of a package and W610 will send received data as a TCP
package data to network. Otherwise W610 will receive data to 4K bytes and send these 4K bytes as a TCP
package data to network. 

Suppose n ms is serial package triggering time, if T1>n, T2<n, T3<n, T4<n, T5<n, T6>n, Byte1-Byte5 will be a
package.

![image](https://user-images.githubusercontent.com/13651344/143958649-478de403-8cf2-4889-a1e0-f688bc31edba.png)

3.2.3.Serial package method
W610 supports serial package method(include Time Trigger Mode and Length Trigger Mode) and W610 will
send received data as TCP package data to network if serial data arrive triggering time or triggering length.

**Comment by blacksocket** [comment]
Still the same issue:

qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No TLS backend is available
qt.network.ssl: No functional TLS backend was found
qt.network.ssl: No functional TLS backend was found
connecting...
connected...
Connected to mqtt broker
15  bytes written...
"^D01100000000\xDC\xC0\r"
8  bytes written...
"^D10100000,00030"
PowerStatus: wrong Format
8  bytes written...
",,+00016,+00013,+00029,+00058,0000,0000,0000,00000,0115,0139,0160,00414,004,1,0,1,1,1,1G\xF1\r^D1100000,3177,0"
GeneralStatus: wrong Format

**Comment by danielschramm** [comment]
Hello, I now read nearly the whole manual. There are a lot of options like the timings for chapter 3.2.2 which are not available in the web interface but can be set via AT Commands like on 1990th dialup modems.
Therefore a second manual exists and also a config software:
https://www.pusr.com/support/downloads/USR-W610-ATSetup_V1.0.4.html
https://www.pusr.com/support/downloads/USR-W610-AT-Command-Set-V100.html

![image](https://user-images.githubusercontent.com/7165994/144115831-afbc5ff9-f020-4320-a86a-5f9cf5c5a0a5.png)

I'm sure the device can be configured to get it running, but it's really the most advanced and complicated serial to network interface I have seen right now.

Good Luck,

Daniel

**Comment by blacksocket** [comment]
Thank you very much Daniel! I will try to configure it in the proper way and let you know about the results.. ;-)
