### ISSUE TITLE
Code compilation on the Ubuntu 20.04.4 LTS

### ISSUE THREAD

**Issue by blacksocket** [danielschramm/qt_inverter_10k#3]
Hello Daniel,

I am trying to compile the code on Ubuntu 20.04.4 LTS. I installed below:
sudo apt install `apt-cache search qt | grep 5- | grep -v gles | grep ^qt | awk '{print $1}' | xargs `
sudo apt install `apt-cache search libqt5 | grep -v gles | grep ^libqt | awk '{print $1}' | xargs`

The Qt version 5.12.8 in /usr/lib/x86_64-linux-gnu has been installed.
Then I downloaded the source 5.12.8 to /qt_inverter_10k/src/qtmqtt/ from
https://github.com/qt/qtmqtt/tree/5.12.8

I have compiled it using below procedure:

mkdir src
cd src
-> checkout correct version to match qt installation from: git://code.qt.io/qt/qtmqtt.git
cd qtmqtt
qmake
gmake
gmake install

The qmake works then I launched the make (gmake don't work probably because lack of alias) and I am getting issue below:

***********************************
ubuntu@mail:/qt_inverter_10k/src/qtmqtt$ qmake
Info: creating stash file /home/ubuntu/qt_inverter_10k/src/qtmqtt/.qmake.stash
Info: creating cache file /home/ubuntu/qt_inverter_10k/src/qtmqtt/.qmake.cache
ubuntu@mail:/qt_inverter_10k/src/qtmqtt$ gmake

Command 'gmake' not found, but there are 14 similar ones.

ubuntu@mail:~/qt_inverter_10k/src/qtmqtt$ make
cd src/ && ( test -e Makefile || /usr/lib/qt5/bin/qmake -o Makefile /home/ubuntu/qt_inverter_10k/src/qtmqtt/src/src.pro ) && make -f Makefile
.......
/usr/lib/qt5/bin/uic mainwindow.ui -o .uic/ui_mainwindow.h
g++ -c -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -O2 -fno-exceptions -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_MQTT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I../../../include -I../../../include/QtMqtt -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I.moc -I.uic -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o .obj/main.o main.cpp

In file included from main.cpp:51:
mainwindow.h:55:10: fatal error: QMqttClient: No such file or directory
   55 | #include <QMqttClient>
      |          ^~~~~~~~~~~~~
compilation terminated.

********************************

Should I add something to the folder include ?

**********************
ubuntu@mail:~/qt_inverter_10k/src/qtmqtt$ ll
total 168
drwxr-xr-x 10 ubuntu ubuntu  4096 Apr 15 12:08 ./
drwxrwxr-x  3 ubuntu ubuntu  4096 Apr 15 12:08 ../
-rw-rw-r--  1 ubuntu ubuntu     0 Apr 15 12:08 .qmake.cache
-rw-r--r--  1 ubuntu ubuntu    71 Mar 17  2020 .qmake.conf
-rw-rw-r--  1 ubuntu ubuntu   687 Apr 15 12:08 .qmake.stash
-rw-r--r--  1 ubuntu ubuntu    41 Mar 17  2020 .tag
-rw-r--r--  1 ubuntu ubuntu 35147 Mar 17  2020 LICENSE.GPL3
-rw-r--r--  1 ubuntu ubuntu 36363 Mar 17  2020 LICENSE.GPL3-EXCEPT
-rw-rw-r--  1 ubuntu ubuntu 36420 Apr 15 12:08 Makefile
drwxrwxr-x  2 ubuntu ubuntu  4096 Apr 15 12:08 bin/
drwxr-xr-x  2 ubuntu ubuntu  4096 Mar 17  2020 dist/
drwxr-xr-x  3 ubuntu ubuntu  4096 Apr 15 12:09 examples/
drwxrwxr-x  3 ubuntu ubuntu  4096 Apr 15 12:08 include/
drwxrwxr-x  4 ubuntu ubuntu  4096 Apr 15 12:09 lib/
drwxrwxr-x  4 ubuntu ubuntu  4096 Apr 15 12:08 mkspecs/
-rw-r--r--  1 ubuntu ubuntu   148 Mar 17  2020 qtmqtt.pro
drwxr-xr-x  3 ubuntu ubuntu  4096 Apr 15 12:08 src/
-rw-r--r--  1 ubuntu ubuntu    99 Mar 17  2020 sync.profile
drwxr-xr-x  5 ubuntu ubuntu  4096 Mar 17  2020 tests/

***************************

ubuntu@mail:~/qt_inverter_10k$ ll src/qtmqtt/include/QtMqtt/
total 12
drwxrwxr-x 2 ubuntu ubuntu 4096 Apr 15 12:08 ./
drwxrwxr-x 3 ubuntu ubuntu 4096 Apr 15 12:08 ../
-rw-rw-r-- 1 ubuntu ubuntu  199 Apr 15 12:08 QtMqttDepends

**Comment by danielschramm** [comment]
Did. You select the correct version of QtMqtt for the installed QT Dev package?

**Comment by blacksocket** [comment]
Hello Daniel,

The Qt version 5.12.8 in /usr/lib/x86_64-linux-gnu has been installed.
Then I downloaded the source 5.12.8 to /qt_inverter_10k/src/qtmqtt/ from
https://github.com/qt/qtmqtt/tree/5.12.8

ubuntu@mail:~/qt_inverter_10k$ qmake -v
QMake version 3.1
Using Qt version 5.12.8 in /usr/lib/x86_64-linux-gnu

Both are in v. 5.12.8. Do you mean another package ?

**Comment by danielschramm** [comment]
Hm, looks good to me. I currently have no idea why it does not work. Either a missing package or strange setting in Ubuntu?
Perhaps you could alternatively try to get a full QT dev
Env from QT website and try to build it with that.
If I find some spare time I can set up a VM to test it as well.

**Comment by blacksocket** [comment]
Finally I was able to fix the issue using the below command instead of coping the zip file from github:
git clone -b 5.12.8 https://github.com/qt/qtmqtt.git
then "qmake", "make" and "sudo make install" works.

What should I do next to build the linux binary of qt_inverter_10k?

I found the solution here:
https://lopeztel.noho.st/gitea/lopeztel/MQTT_Dashboard/src/commit/3a064ff9bf73fc5efdf924e46239b8d3b343e9dc/Qt%20compilation%20and%20instalation%20guide.md
